services:
  nginx:
    extends:
      file: ./compose/nginx.yaml
      service: nginx

  sdc-ide-web:
    image: bedasoftware/sdc-ide:master
    environment:
      BASE_URL: "https:\\/\\/aidbox.sdc.beda.software\\/"

  sdc-ide-web-healthcheck:
    extends:
      file: ./compose/sdc-ide-web-healthcheck.yaml
      service: sdc-ide-web-healthcheck

  sdc-ide-backend:
    extends:
      file: ./compose/sdc-ide-backend.yaml
      service: sdc-ide-backend

  sdc-ide-aidbox:
    extends:
      file: ./compose/sdc-ide-aidbox.yaml
      service: sdc-ide-aidbox

  sdc-ide-aidbox-db:
    # Update version
    image: healthsamurai/aidboxdb:13.2
    environment:
      POSTGRES_USER:     ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB:       ${POSTGRES_DB:-devbox}

  sdc-ide-aidbox-healthcheck:
    extends:
      file: ./compose/sdc-ide-aidbox-healthcheck.yaml
      service: sdc-ide-aidbox-healthcheck

  fhir-emr-web:
    image: bedasoftware/fhir-emr:master
    environment:
      BASE_URL: "https:\\/\\/aidbox.emr.beda.software\\/"

  fhir-emr-web-healthcheck:
    extends:
      file: ./compose/fhir-emr-web-healthcheck.yaml
      service: fhir-emr-web-healthcheck

  fhir-emr-sdc:
    extends:
      file: ./compose/fhir-emr-sdc.yaml
      service: fhir-emr-sdc

  fhir-emr-aidbox:
    extends:
      file: ./compose/fhir-emr-aidbox.yaml
      service: fhir-emr-aidbox

  fhir-emr-aidbox-db:
    # Update version
    image: healthsamurai/aidboxdb:13.2
    environment:
      POSTGRES_USER:     ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB:       ${POSTGRES_DB:-devbox}

  fhir-emr-aidbox-healthcheck:
    extends:
      file: ./compose/fhir-emr-aidbox-healthcheck.yaml
      service: fhir-emr-aidbox-healthcheck

  fhir-emr-scheduling:
    extends:
      file: ./compose/fhir-emr-scheduling.yaml
      service: fhir-emr-scheduling

  fhir-datasequence-ingestion-api:
    extends:
      file: ./compose/fhir-datasequence-ingestion-api.yaml
      service: fhir-datasequence-ingestion-api

  fhir-datasequence-ingestion-api-migrations:
    extends:
      file: ./compose/fhir-datasequence-ingestion-api-migrations.yaml
      service: fhir-datasequence-ingestion-api-migrations

  fhir-datasequence-timescaledb:
    extends:
      file: ./compose/fhir-datasequence-timescaledb.yaml
      service: fhir-datasequence-timescaledb

  build-seeds:
    build:
      context: /root/fhir-emr-master/.
      dockerfile: /root/fhir-emr-master/Dockerfile.seeds
    volumes:
      - /root/fhir-emr-master/zrc:/app/zrc
      - /root/fhir-emr-master/resources/seeds:/app/resources/seeds
