services:
  nginx:
    image: jonasal/nginx-certbot
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx:/etc/nginx/user_conf.d:ro
    - ./letsencrypt:/etc/letsencrypt
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
    depends_on:
      sdc-ide-aidbox-healthcheck:
        condition:
          service_healthy
      sdc-ide-web-healthcheck:
        condition:
          service_healthy
      fhir-emr-aidbox-healthcheck:
        condition:
          service_healthy
      fhir-emr-web-healthcheck:
        condition:
          service_healthy

  sdc-ide-web:
    image: bedasoftware/sdc-ide:master
    environment:
      BASE_URL: "https:\\/\\/aidbox.sdc.beda.software\\/"

  sdc-ide-web-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - sdc-ide-web
    depends_on:
      - sdc-ide-web
    healthcheck:
      test: curl --fail http://sdc-ide-web:5000 || exit 1
      interval: 1s
      timeout: 20s
      retries: 100

  sdc-ide-backend:
    image: bedasoftware/aidbox-sdc:latest
    depends_on:
      sdc-ide-aidbox-healthcheck:
        condition:
          service_healthy
    links:
      - sdc-ide-aidbox
    env_file:
      - .env.sdc-ide
    # Colored logs
    tty: true

  sdc-ide-aidbox:
    image: healthsamurai/aidboxone:edge
    depends_on:
      - sdc-ide-aidbox-db
    links:
      - sdc-ide-aidbox-db:database
    env_file:
      - .env.sdc-ide
    environment:
      AIDBOX_LICENSE: ${SDC_IDE_AIDBOX_LICENSE}
      AIDBOX_ADMIN_PASSWORD: ${SDC_IDE_AIDBOX_ADMIN_PASSWORD:-password}
    volumes:
      - ./config:/var/config:cached

  sdc-ide-aidbox-db:
    # Update version
    image: healthsamurai/aidboxdb:13.2
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}

  sdc-ide-aidbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - sdc-ide-aidbox
    depends_on:
      - sdc-ide-aidbox
    healthcheck:
      test: curl --fail http://sdc-ide-aidbox:8080/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100

  fhir-emr-web:
    image: bedasoftware/fhir-emr:master
    environment:
      BASE_URL: "https:\\/\\/aidbox.fhir-emr.beda.software\\/"

  fhir-emr-web-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - fhir-emr-web
    depends_on:
      - fhir-emr-web
    healthcheck:
      test: curl --fail http://fhir-emr-web:5000 || exit 1
      interval: 1s
      timeout: 20s
      retries: 100

  fhir-emr-sdc:
    image: bedasoftware/aidbox-sdc:latest
    depends_on:
      fhir-emr-aidbox-healthcheck:
        condition:
          service_healthy
    links:
      - fhir-emr-aidbox
    env_file:
      - .env.fhir-emr
    # Colored logs
    tty: true

  fhir-emr-aidbox:
    image: healthsamurai/aidboxone:edge
    depends_on:
      - fhir-emr-aidbox-db
    links:
      - fhir-emr-aidbox-db:database
    env_file:
      - .env.fhir-emr
    environment:
      AIDBOX_LICENSE: ${FHIR_EMR_AIDBOX_LICENSE}
      AIDBOX_ADMIN_PASSWORD: ${FHIR_EMR_AIDBOX_ADMIN_PASSWORD:-password}
    volumes:
      - ./config:/var/config:cached
      - /root/fhir-emr-master/zrc:/zrc

  fhir-emr-aidbox-db:
    # Update version
    image: healthsamurai/aidboxdb:13.2
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       devbox

  fhir-emr-aidbox-healthcheck:
    image: curlimages/curl
    entrypoint: /bin/sleep 10000
    links:
      - fhir-emr-aidbox
    depends_on:
      - fhir-emr-aidbox
    healthcheck:
      test: curl --fail http://fhir-emr-aidbox:8080/__healthcheck || exit 1
      interval: 1s
      timeout: 20s
      retries: 100

  build-seeds:
    build:
      context: /root/fhir-emr-master/.
      dockerfile: /root/fhir-emr-master/Dockerfile.seeds
    volumes:
      - /root/fhir-emr-master/zrc:/app/zrc
      - /root/fhir-emr-master/resources/seeds:/app/resources/seeds
