services:
  fhir-datasequence-timescaledb:
    image: timescale/timescaledb:latest-pg15
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${TIMESCALEDB_POSTGRES_PASSWORD:-timescaledb-password}
