name: Deploy video conference server configs
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.VIDEO_REMOTE_HOST}}
          username: ${{secrets.VIDEO_REMOTE_USER}}
          key: ${{secrets.VIDEO_SSH_PRIVATE_KEY}}
          source: "jitsi/*,!/jitsi/cfg-backup.bz2"
          target: "jitsi-meet-tmp"
      - name: Generate .env and restart
        uses: appleboy/ssh-action@v0.1.7
        env:
          CONFIG: ${{secrets.VIDEO_CONFIG_PATH}}
          PUBLIC_URL: ${{secrets.VIDEO_PUBLIC_URL}}
          LETSENCRYPT_DOMAIN: ${{secrets.VIDEO_REMOTE_HOST}}
          LETSENCRYPT_EMAIL: ${{secrets.CERTBOT_EMAIL}}
          JICOFO_AUTH_PASSWORD: ${{secrets.JICOFO_AUTH_PASSWORD}}
          JVB_AUTH_PASSWORD: ${{secrets.JVB_AUTH_PASSWORD}}
        with:
          host: ${{secrets.VIDEO_REMOTE_HOST}}
          username: ${{secrets.VIDEO_REMOTE_USER}}
          key: ${{secrets.VIDEO_SSH_PRIVATE_KEY}}
          envs: CONFIG,PUBLIC_URL,LETSENCRYPT_DOMAIN,LETSENCRYPT_EMAIL,JICOFO_AUTH_PASSWORD,JVB_AUTH_PASSWORD
          script_stop: true
          script: |
            cp ~/jitsi-meet-tmp/jitsi/* ~/jitsi-meet
            cd ~/jitsi-meet
            mv compose.jitsi.yaml compose.yaml
            mv .env.jitsi .env
            make restart
            rm -rf ~/jitsi-meet-tmp
            echo Current branch is ${{ github.ref }}
